{
    "columns": [
        { "header": "Product Name", "mandatory": true, "language": "en" },
        { "header": "Seller Stock Code", "mandatory": true, "language": "en" },
        { "header": "Barcode", "mandatory": true, "language": "en" },
        { "header": "Variant Group Id", "mandatory": false, "language": "en" },
        { "header": "Product Description", "mandatory": true, "language": "en" },
        { "header": "Brand", "mandatory": true, "language": "en" },
        { "header": "Desi", "mandatory": true, "language": "en" },
        { "header": "VAT", "mandatory": true, "language": "en" },
        { "header": "Warranty Period (Months)", "mandatory": true, "language": "en" },
        { "header": "Image1", "mandatory": false, "language": "en" },
        { "header": "Image2", "mandatory": false, "language": "en" },
        { "header": "Image3", "mandatory": false, "language": "en" },
        { "header": "Image4", "mandatory": false, "language": "en" },
        { "header": "Image5", "mandatory": false, "language": "en" },

        { "header": "Tuotteen nimi", "mandatory": true, "language": "fi" },
        { "header": "Myyjän varastokoodi", "mandatory": true, "language": "fi" },
        { "header": "Viivakoodi", "mandatory": true, "language": "fi" },
        { "header": "Vaihtoehtoinen ryhmä tunnus", "mandatory": false, "language": "fi" },
        { "header": "Tuotteen kuvaus", "mandatory": true, "language": "fi" },
        { "header": "Merkki", "mandatory": true, "language": "fi" },
        { "header": "Desi", "mandatory": true, "language": "fi" },
        { "header": "ALV", "mandatory": true, "language": "fi" },
        { "header": "Takuuaika (kuukausina)", "mandatory": true, "language": "fi" },
        { "header": "Kuva1", "mandatory": false, "language": "fi" },
        { "header": "Kuva2", "mandatory": false, "language": "fi" },
        { "header": "Kuva3", "mandatory": false, "language": "fi" },
        { "header": "Kuva4", "mandatory": false, "language": "fi" },
        { "header": "Kuva5", "mandatory": false, "language": "fi" },

        { "header": "Produktnamn", "mandatory": true, "language": "sv" },
        { "header": "Säljarens lagerkod", "mandatory": true, "language": "sv" },
        { "header": "Streckkod", "mandatory": true, "language": "sv" },
        { "header": "Variantgruppid", "mandatory": false, "language": "sv" },
        { "header": "Produktbeskrivning", "mandatory": true, "language": "sv" },
        { "header": "Varumärke", "mandatory": true, "language": "sv" },
        { "header": "Desi", "mandatory": true, "language": "sv" },
        { "header": "Moms", "mandatory": true, "language": "sv" },
        { "header": "Garantiperiod (månader)", "mandatory": true, "language": "sv" },
        { "header": "Bild1", "mandatory": false, "language": "sv" },
        { "header": "Bild2", "mandatory": false, "language": "sv" },
        { "header": "Bild3", "mandatory": false, "language": "sv" },
        { "header": "Bild4", "mandatory": false, "language": "sv" },
        { "header": "Bild5", "mandatory": false, "language": "sv" },

        { "header": "Produktnavn", "mandatory": true, "language": "no" },
        { "header": "Selgers lagerkode", "mandatory": true, "language": "no" },
        { "header": "Strekkode", "mandatory": true, "language": "no" },
        { "header": "Variantgruppe-ID", "mandatory": false, "language": "no" },
        { "header": "Produktbeskrivelse", "mandatory": true, "language": "no" },
        { "header": "Merke", "mandatory": true, "language": "no" },
        { "header": "Desi", "mandatory": true, "language": "no" },
        { "header": "MVA", "mandatory": true, "language": "no" },
        { "header": "Garantiperiode (måneder)", "mandatory": true, "language": "no" },
        { "header": "Bilde1", "mandatory": false, "language": "no" },
        { "header": "Bilde2", "mandatory": false, "language": "no" },
        { "header": "Bilde3", "mandatory": false, "language": "no" },
        { "header": "Bilde4", "mandatory": false, "language": "no" },
        { "header": "Bilde5", "mandatory": false, "language": "no" },

        { "header": "Produktnavn", "mandatory": true, "language": "da" },
        { "header": "Sælgers lagerkode", "mandatory": true, "language": "da" },
        { "header": "Stregkode", "mandatory": true, "language": "da" },
        { "header": "Variantgruppe ID", "mandatory": false, "language": "da" },
        { "header": "Produktbeskrivelse", "mandatory": true, "language": "da" },
        { "header": "Mærke", "mandatory": true, "language": "da" },
        { "header": "Desi", "mandatory": true, "language": "da" },
        { "header": "Moms", "mandatory": true, "language": "da" },
        { "header": "Garantiperiode (måneder)", "mandatory": true, "language": "da" },
        { "header": "Billede1", "mandatory": false, "language": "da" },
        { "header": "Billede2", "mandatory": false, "language": "da" },
        { "header": "Billede3", "mandatory": false, "language": "da" },
        { "header": "Billede4", "mandatory": false, "language": "da" },
        { "header": "Billede5", "mandatory": false, "language": "da" }
    ]
}
